# Generated by Django 3.1.7 on 2021-03-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagnum', models.IntegerField(default=0)),
                ('shot', models.CharField(max_length=225)),
                ('wormer', models.CharField(max_length=225)),
            ],
        ),
    ]
