# Generated by Django 3.1.7 on 2021-03-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='abnormalities',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
