# Generated by Django 3.1.7 on 2021-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_submitmodel_abnormalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
