# Generated by Django 3.1.7 on 2021-03-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_submitmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitmodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
