# Generated by Django 3.1.7 on 2021-03-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210316_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.ImageField(null=True, upload_to='C:/Users/Kaiden Thrailkill/Desktop/Environment/cattle/media_cdn'),
        ),
    ]
