# Generated by Django 3.1.7 on 2021-03-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210316_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.ImageField(default=0, upload_to='C:/Users/Kaiden Thrailkill/Desktop/Environment/cattle/cattle/media'),
            preserve_default=False,
        ),
    ]
