# Generated by Django 3.1.7 on 2021-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210316_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.FileField(upload_to='C:/Users/Kaiden Thrailkill/Desktop/Environment/cattle/cattle/media_cdn/'),
        ),
    ]
