# Generated by Django 3.1.7 on 2021-03-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210316_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.FileField(upload_to='', verbose_name='uploads/% Y/% m/% d/'),
        ),
    ]
