# Generated by Django 3.1.7 on 2021-03-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210316_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.BinaryField(null=True),
        ),
    ]
