# Generated by Django 3.1.7 on 2021-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210316_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
