# Generated by Django 3.1.7 on 2021-03-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210317_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.FileField(default=0, upload_to='cows/'),
        ),
    ]
