# Generated by Django 3.1.7 on 2021-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210317_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='cows'),
        ),
    ]
