# Generated by Django 3.1.7 on 2021-03-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210317_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
