# Generated by Django 3.1.7 on 2021-03-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210317_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
