# Generated by Django 3.1.7 on 2021-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210317_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='pic',
            field=models.BinaryField(null=True),
        ),
    ]
