# Generated by Django 3.1.7 on 2021-03-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210317_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitmodel',
            old_name='shot',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='submitmodel',
            old_name='abnormalities',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='submitmodel',
            old_name='wormer',
            new_name='sex',
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
