# Generated by Django 3.1.7 on 2021-03-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210317_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='dam',
            field=models.IntegerField(default='none'),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='sire',
            field=models.IntegerField(default='none'),
        ),
    ]
