# Generated by Django 3.1.7 on 2021-03-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210317_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='owner',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='pasture',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
