# Generated by Django 3.1.7 on 2021-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210318_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='dam',
            field=models.SlugField(default=0),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='sire',
            field=models.SlugField(default=0),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='tagnum',
            field=models.SlugField(default=0),
        ),
    ]
