# Generated by Django 3.1.7 on 2021-04-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_submitmodel_calfsex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitmodel',
            name='calfsex',
        ),
    ]
