# Generated by Django 3.2.5 on 2021-07-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_submitmodel_calfsex'),
    ]

    operations = [
        migrations.CreateModel(
            name='OWNER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PASTURE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.owner'),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='pasture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.pasture'),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.sex'),
        ),
    ]
