# Generated by Django 3.2.5 on 2021-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_submitmodel_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='dam',
            field=models.SlugField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='sire',
            field=models.SlugField(default=0, null=True),
        ),
    ]
